name: Cypress Tests 

on:
  repository_dispatch:
    types: [chrome]

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Firefox
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
